### ISSUE TITLE
Change the placeholder text

### ISSUE THREAD

**Issue by jhollway** [jhollway/iheiddown#32] opened 2020-10-01 18:28 UTC
When printing just a single chapter with `chapter_pdf()`, the section titles of all the other chapters are included in addition and some 'placeholder' text is entered under some of these extra section titles. These extra section titles either should not appear or appear only in the table of contents printed at the start of the chapter preview.

**Comment by BBieri** [comment] 2021-01-04 17:36
# Update 04.01.2021
The issue seems to stem from the bookdown function *preview_chapter()* [Doc Here](https://bookdown.org/yihui/bookdown/preview-a-chapter.html). The documentation, as well as previous issues, have mentionned it on Github and the response from Yi Hui is that this is done by design. 

## Check out:
- [This](https://github.com/rstudio/bookdown/issues/497)

**Comment by jhollway** [comment] 2021-01-04 17:55
I think I actually solved this issue in a previous change. `chapter_pdf()` should use `{rmarkdown}` not `{bookdown}` any longer. If this is true, you can close this issue and create a new issue for the other placeholder issue I mentioned: re Harry Potter ( for @EstherPeev )

**Comment by BBieri** [comment] 2021-01-04 18:38
@jhollway Thanks for the feedback. In the latest version of iheiddown (I pulled today), `chapter_pdf()` uses bookdown's function to render one chapter at a time. I'll check out a workaround with `{rmarkdown}` tomorrow first thing in the morning. 

I solved the "Harry Potter issue"  today by replacing it by LOTR references. Thus, I'll close this issue for now and will create another one for the issue mentioned above.

**Closed** 2021-01-04 18:39 UTC
Labels: bug
